scara:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint1
    pid: {p: 100.0, i: 5, d: 35.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint2
    pid: {p: 50.0, i: 0, d: 2}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint3
    pid: {p: 4000.0, i: 0, d: 1.0}
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: table_joint
    pid: {p: 15.0, i: 1.5, d: 8.0}

  # Velocity Controllers ---------------------------------------
  joint1_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: joint1
    pid: {p: 10.0, i: 0.02, d: 0.4}
  joint2_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: joint2
    pid: {p: 10, i: 0.02, d: 0.4}
  joint3_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: joint3
    pid: {p: 8, i: 0.01, d: 0}
  joint4_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: table_joint
    pid: {p: 1, i: 0.0, d: 0}